# Generated by Django 3.1.13 on 2022-11-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='level',
            field=models.CharField(choices=[('1', 'normal'), ('2', 'principal'), ('3', 'admin')], max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='sex',
            field=models.CharField(choices=[('1', 'boy'), ('2', 'girl')], max_length=5),
        ),
    ]
