# Generated by Django 3.1.13 on 2022-11-17 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20221117_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='Location',
            new_name='location',
        ),
    ]
