# Generated by Django 3.1.13 on 2022-11-26 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20221117_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='memberNumber',
            new_name='id',
        ),
    ]
