# Generated by Django 3.1.13 on 2022-11-26 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_auto_20221126_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='session',
        ),
    ]
