# Generated by Django 3.1.13 on 2022-11-27 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_remove_member_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='clubNumber',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='principal',
        ),
    ]
