# Generated by Django 4.1.4 on 2022-12-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_alter_activity_id_alter_attend_id_alter_join_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='level',
            field=models.CharField(choices=[('1', 'normal'), ('2', 'principal')], max_length=10),
        ),
    ]
